name: Check broken links

on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
  - cron: '0 11 * * 1'    # run at 11.00 every Monday

jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: broken-link-check
      uses: celinekurpershoek/link-checker@v1.0.2
      with:
        url: "https://ozgurakgun.github.io"
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
