name: Check broken links

on:
  workflow_dispatch:
  schedule:
  - cron: '0 11 * * 1'    # run at 11.00 every Monday

jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: Broken Link Checker
      uses: technote-space/broken-link-checker-action@v2.3.1
      with:
        TARGET: https://ozgurakgun.github.io
